### ISSUE TITLE
Archive can be too big

### ISSUE THREAD

**Issue by rylixs** [alkihis/archive-explorer-web#1]

**Comment by alkihis** [comment]
This is a JSZip limitation of 4GB archives. Must extract zip, remove tweet_media directory and re-compress folder. Documentation to do + message to the end user. Might not be fixed.

**Comment by alkihis** [comment]
Documented in website, alert message displayed. Should be documented in README.md.

**Comment by alkihis** [comment]
Fixed in 1.1.1 using a Blob streaming method.
