### ISSUE TITLE
I can't log back in

### ISSUE THREAD

**Issue by sHall0w** [alkihis/archive-explorer-web#27]
Hello, I have a problem logging into Archive Explorer. It worked just fine before, then now it said something about credentials expired and that i have to log in again, but it won't let me log back in. I get this message:

![image](https://github.com/alkihis/archive-explorer-web/assets/94927832/1690c168-02a9-4eb5-911b-a3c95354fee5)

I tried logging in in a different web browser, or on phone, or using a different account, but I get this same message every time. I looked at my Twitter settings as well, but I couldn't find anything that helped. Could you please help me?

**Comment by alkihis** [comment]
Twitter has revoked access and suspended the application because it doesn't complies with new absurd API rules made by Musk.
This project is now dead.
