### ISSUE TITLE
Can't remove favourites (AKA likes)?

### ISSUE THREAD

**Issue by chrisbeach** [alkihis/archive-explorer-web#7]
Can you please add a feature to remove likes

**Comment by alkihis** [comment]
Hello, 
Unfortunately Twitter has a problem with favorites removal ; when fav is older than several months, asking Twitter to remove it will do nothing.
It is why favorites deletion is not available on Archive Explorer.

**Comment by chrisbeach** [comment]
Ah, thanks for letting me know
